# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\add_usluga.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 371, 261))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.fam = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fam.setFont(font)
        self.fam.setObjectName("fam")
        self.nameEdit = QtWidgets.QLineEdit(self.splitter)
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.name = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.costEdit = QtWidgets.QLineEdit(self.splitter)
        self.costEdit.setText("")
        self.costEdit.setObjectName("costEdit")
        self.fath = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fath.setFont(font)
        self.fath.setObjectName("fath")
        self.timeEdit = QtWidgets.QTimeEdit(self.splitter)
        self.timeEdit.setObjectName("timeEdit")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fam.setText(_translate("Dialog", "Название"))
        self.name.setText(_translate("Dialog", "Цена"))
        self.fath.setText(_translate("Dialog", "Длительность"))
        self.pushButton.setText(_translate("Dialog", "OK"))
