# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\add_customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 309)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fam = QtWidgets.QLabel(Dialog)
        self.fam.setObjectName("fam")
        self.verticalLayout.addWidget(self.fam)
        self.famEdit = QtWidgets.QLineEdit(Dialog)
        self.famEdit.setObjectName("famEdit")
        self.verticalLayout.addWidget(self.famEdit)
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.fath = QtWidgets.QLabel(Dialog)
        self.fath.setObjectName("fath")
        self.verticalLayout.addWidget(self.fath)
        self.fathEdit = QtWidgets.QLineEdit(Dialog)
        self.fathEdit.setObjectName("fathEdit")
        self.verticalLayout.addWidget(self.fathEdit)
        self.phone = QtWidgets.QLabel(Dialog)
        self.phone.setObjectName("phone")
        self.verticalLayout.addWidget(self.phone)
        self.phoneEdit = QtWidgets.QLineEdit(Dialog)
        self.phoneEdit.setValidator(QtGui.QIntValidator())
        self.phoneEdit.setInputMask("")
        self.phoneEdit.setMaxLength(12)
        self.phoneEdit.setObjectName("phoneEdit")
        self.verticalLayout.addWidget(self.phoneEdit)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление клиента"))
        self.fam.setText(_translate("Dialog", "Фамилия"))
        self.famEdit.setText(_translate("Dialog", "Иванов"))
        self.name.setText(_translate("Dialog", "Имя"))
        self.nameEdit.setText(_translate("Dialog", "Иван"))
        self.fath.setText(_translate("Dialog", "Отчество"))
        self.fathEdit.setText(_translate("Dialog", "Иван"))
        self.phone.setText(_translate("Dialog", "Телефон"))
        self.phoneEdit.setText(_translate("Dialog", "380660991234"))
        self.pushButton.setText(_translate("Dialog", "OK"))
