# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\add_employee.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(394, 432)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.famEdit = QtWidgets.QLineEdit(Dialog)
        self.famEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.famEdit.setObjectName("famEdit")
        self.verticalLayout.addWidget(self.famEdit)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.fathEdit = QtWidgets.QLineEdit(Dialog)
        self.fathEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.fathEdit.setObjectName("fathEdit")
        self.verticalLayout.addWidget(self.fathEdit)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.moneyEdit = QtWidgets.QLineEdit(Dialog)
        self.moneyEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.moneyEdit.setInputMask("")
        self.moneyEdit.setText("")
        self.moneyEdit.setMaxLength(32767)
        self.moneyEdit.setObjectName("moneyEdit")
        self.verticalLayout.addWidget(self.moneyEdit)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.phoneEdit = QtWidgets.QLineEdit(Dialog)
        self.phoneEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.phoneEdit.setInputMask("")
        self.phoneEdit.setText("")
        self.phoneEdit.setMaxLength(32767)
        self.phoneEdit.setObjectName("phoneEdit")
        self.verticalLayout.addWidget(self.phoneEdit)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 22))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 22))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление сотрудника"))
        self.label.setText(_translate("Dialog", "Фамилия"))
        self.label_5.setText(_translate("Dialog", "Имя"))
        self.label_6.setText(_translate("Dialog", "Отчество"))
        self.label_3.setText(_translate("Dialog", "Ставка"))
        self.label_7.setText(_translate("Dialog", "Телефон"))
        self.label_2.setText(_translate("Dialog", "Дата приема"))
        self.label_4.setText(_translate("Dialog", "Специализация"))
        self.pushButton.setText(_translate("Dialog", "Добавить"))
