# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\add_auto_cust.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(328, 394)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 55, 16))
        self.label_2.setObjectName("label_2")
        self.markAuto = QtWidgets.QComboBox(Dialog)
        self.markAuto.setGeometry(QtCore.QRect(20, 40, 131, 22))
        self.markAuto.setObjectName("markAuto")
        self.modelAuto = QtWidgets.QComboBox(Dialog)
        self.modelAuto.setGeometry(QtCore.QRect(170, 40, 131, 22))
        self.modelAuto.setObjectName("modelAuto")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 131, 22))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 280, 55, 22))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.numberEdit = QtWidgets.QLineEdit(Dialog)
        self.numberEdit.setGeometry(QtCore.QRect(170, 100, 131, 22))
        self.numberEdit.setObjectName("numberEdit")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(170, 80, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 131, 22))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 220, 131, 22))
        self.label_8.setObjectName("label_8")
        self.famList = QtWidgets.QComboBox(Dialog)
        self.famList.setGeometry(QtCore.QRect(20, 130, 291, 22))
        self.famList.setObjectName("famList")
        self.nameList = QtWidgets.QComboBox(Dialog)
        self.nameList.setGeometry(QtCore.QRect(20, 190, 291, 22))
        self.nameList.setObjectName("nameList")
        self.fathList = QtWidgets.QComboBox(Dialog)
        self.fathList.setGeometry(QtCore.QRect(20, 250, 291, 22))
        self.fathList.setObjectName("fathList")
        self.phoneList = QtWidgets.QComboBox(Dialog)
        self.phoneList.setGeometry(QtCore.QRect(20, 310, 291, 22))
        self.phoneList.setObjectName("phoneList")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Марка"))
        self.label_2.setText(_translate("Dialog", "Модель"))
        self.label_4.setText(_translate("Dialog", "Фамилия клиента"))
        self.label_5.setText(_translate("Dialog", "Телефон"))
        self.pushButton.setText(_translate("Dialog", "Добавить"))
        self.numberEdit.setPlaceholderText(_translate("Dialog", "AA####AA"))
        self.label_6.setText(_translate("Dialog", "Гос номер"))
        self.label_7.setText(_translate("Dialog", "Имя клиента"))
        self.label_8.setText(_translate("Dialog", "Отчество клиента"))
