# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\insert_customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 223)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 180, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label.setObjectName("label")
        self.fioEdit = QtWidgets.QLineEdit(Dialog)
        self.fioEdit.setGeometry(QtCore.QRect(20, 50, 441, 22))
        self.fioEdit.setObjectName("fioEdit")
        self.phoneEdit = QtWidgets.QLineEdit(Dialog)
        self.phoneEdit.setGeometry(QtCore.QRect(20, 130, 441, 22))
        self.phoneEdit.setInputMask("")
        self.phoneEdit.setObjectName("phoneEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 55, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.label.setText(_translate("Dialog", "Фио"))
        self.fioEdit.setText(_translate("Dialog", "Иванов Иван Иванович"))
        self.phoneEdit.setText(_translate("Dialog", "381234567890"))
        self.label_2.setText(_translate("Dialog", "Телефон"))
