# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\add_customer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 309)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.fam = QtWidgets.QLabel(Dialog)
        self.fam.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.fam.setObjectName("fam")
        self.famEdit = QtWidgets.QLineEdit(Dialog)
        self.famEdit.setGeometry(QtCore.QRect(20, 50, 301, 22))
        self.famEdit.setObjectName("famEdit")
        self.phoneEdit = QtWidgets.QLineEdit(Dialog)
        self.phoneEdit.setGeometry(QtCore.QRect(120, 230, 201, 22))
        self.phoneEdit.setInputMask("")
        self.phoneEdit.setObjectName("phoneEdit")
        self.phone = QtWidgets.QLabel(Dialog)
        self.phone.setGeometry(QtCore.QRect(20, 230, 55, 16))
        self.phone.setObjectName("phone")
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(20, 90, 55, 16))
        self.name.setObjectName("name")
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setGeometry(QtCore.QRect(20, 120, 301, 22))
        self.nameEdit.setObjectName("nameEdit")
        self.fathEdit = QtWidgets.QLineEdit(Dialog)
        self.fathEdit.setGeometry(QtCore.QRect(20, 190, 301, 22))
        self.fathEdit.setObjectName("fathEdit")
        self.fath = QtWidgets.QLabel(Dialog)
        self.fath.setGeometry(QtCore.QRect(20, 160, 55, 16))
        self.fath.setObjectName("fath")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.fam.setText(_translate("Dialog", "Фамилия"))
        self.famEdit.setText(_translate("Dialog", "Иванов"))
        self.phoneEdit.setText(_translate("Dialog", "381234567890"))
        self.phone.setText(_translate("Dialog", "Телефон"))
        self.name.setText(_translate("Dialog", "Имя"))
        self.nameEdit.setText(_translate("Dialog", "Иван"))
        self.fathEdit.setText(_translate("Dialog", "Иванович"))
        self.fath.setText(_translate("Dialog", "Отчество"))
