# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\detail_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(472, 316)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.uslugaEdit = QtWidgets.QLineEdit(Dialog)
        self.uslugaEdit.setReadOnly(True)
        self.uslugaEdit.setObjectName("uslugaEdit")
        self.verticalLayout.addWidget(self.uslugaEdit)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.partEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.partEdit.setFont(font)
        self.partEdit.setReadOnly(True)
        self.partEdit.setObjectName("partEdit")
        self.verticalLayout.addWidget(self.partEdit)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.endTime = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.endTime.setFont(font)
        self.endTime.setReadOnly(True)
        self.endTime.setObjectName("endTime")
        self.verticalLayout.addWidget(self.endTime)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.emplSpec = QtWidgets.QLineEdit(Dialog)
        self.emplSpec.setReadOnly(True)
        self.emplSpec.setObjectName("emplSpec")
        self.verticalLayout.addWidget(self.emplSpec)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.emplEdit = QtWidgets.QLineEdit(Dialog)
        self.emplEdit.setReadOnly(True)
        self.emplEdit.setObjectName("emplEdit")
        self.verticalLayout.addWidget(self.emplEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Новая задача"))
        self.label_8.setText(_translate("Dialog", "Услуга:"))
        self.label_2.setText(_translate("Dialog", "Запчасть:"))
        self.label_3.setText(_translate("Dialog", "Выполнить до:"))
        self.label_7.setText(_translate("Dialog", "Специальность сотрудника"))
        self.label_4.setText(_translate("Dialog", "Сотрудник"))
